# Generated by Django 5.1.2 on 2024-11-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagemodel',
            new_name='Projectmodel',
        ),
    ]
