# Generated by Django 5.1 on 2024-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_image', models.FileField(upload_to='Document/')),
                ('project_location', models.CharField(max_length=250)),
                ('Uploader_name', models.CharField(max_length=250)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('people_working', models.IntegerField()),
            ],
        ),
    ]
