# Generated by Django 5.1.2 on 2024-11-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0002_rename_imagemodel_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_id',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view_app.projectmodel')),
                ('worker', models.ManyToManyField(blank=True, to='view_app.worker')),
            ],
        ),
    ]
