# Generated by Django 5.1.2 on 2024-10-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0002_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='Uploader_name',
            new_name='uploaded_by',
        ),
    ]
