# Generated by Django 5.1.2 on 2024-11-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0004_logintoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginToken',
        ),
    ]
