# Generated by Django 5.1.2 on 2024-11-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0004_bricksmodel_cementmodel_gravelmodel_sandmodel'),
        ('view_app', '0004_worker'),
    ]

    operations = [
    ]
